### ISSUE TITLE
Should Fragile use ManuallyDrop instead of MaybeUninit?

### ISSUE THREAD

**Issue by anp** [mitsuhiko/fragile#11]
I [had this question](https://fuchsia-review.googlesource.com/c/fuchsia/+/453634/2/third_party/rust_crates/vendor/fragile/src/fragile.rs#28) while reviewing this crate for vendoring in another project.

**Comment by mitsuhiko** [comment]
This crate used to use `ManuallyDrop`. The way this is used though is one of the reasons that `MaybeUninit` has been created (eg: working with uninitialized bytes) so I decided to switch. The exact rules on uninitialized memory in Rust are tricky and `MaybeUninit` makes it slightly saner.
