### ISSUE TITLE
Why does Sticky's registry thread local need to be wrapped in UnsafeCell?

### ISSUE THREAD

**Issue by anp** [mitsuhiko/fragile#12]
IIUC, all access to the thread-local is done mutably through `with(|registry| ...)` calls, so why does this need to be wrapped for unsafe mutable access?

https://github.com/mitsuhiko/rust-fragile/blob/ffcb16e17c018ef0442c8fc36d6b0defeaba6486/src/sticky.rs#L28

**Comment by mitsuhiko** [comment]
Well it needs a cell to become mutable. An alternative version would use `RefCell` but that has a runtime impact.
