### ISSUE TITLE
Unsoundness: `Sticky` can keep values longer than their lifetime

### ISSUE THREAD

**Issue by SabrinaJewson** [mitsuhiko/fragile#15]
```rs
fn main() {
    let boxed = Box::new(5);
    let sticky = fragile::Sticky::new(Helper(&boxed));
    crossbeam::scope(|s| { s.spawn(|_| drop(sticky)); }).unwrap();
}

struct Helper<'a>(&'a i32);
impl Drop for Helper<'_> {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}
```

This code prints out an uninitialized value or segfaults because `boxed` is dropped before `Helper` is. I think the solution here is to require `'static` on values held in a `Sticky`.

**Comment by mitsuhiko** [comment]
This is worrying. I need to re-evaluate this. I'm not sure if the static bound will solve this and I'm also not sure if `Fragile` itself is okay now.
