### ISSUE TITLE
change thread ownership

### ISSUE THREAD

**Issue by cehteh** [mitsuhiko/fragile#24]
Did you consider to add a function to transfer the ownership of a Fragile or Sticky cell to another thread?

 * This is safe when the current owning thread does it as last action it does on this object. From there on the receiving thread is responsible.
 * A slight disadvantage would be that thread ID's are not an implementation feature anymore but need to be passed over the API
 * How one the current owning thread gets the thread ID of the new owner could/should be deliberately left out. The ownership transfer usually needs some synchronization (cond-var, channel, ...) to be done by the user.

**Comment by mitsuhiko** [comment]
I have thought about it but I figured that that's beyond of what I can reason about. In particular it significantly invalidates the assumptions a non `Send` object might have about the state of the world. For instance it might use unsafe code internally that upholds invariants via thread locals.

**Comment by mitsuhiko** [comment]
I guess the question is if there is a point in having an unsafe API that would allow you to move the object, but I have a hard time imagining how this would be useful in practice.

**Comment by cehteh** [comment]
OK for me when you close this, i had a slightly different use case which on closer inspection wasn't a good match for 'fragile', eventually I made https://crates.io/crates/threadcell which covers my use-case.
