### ISSUE TITLE
Add Rust version requirements to the README

### ISSUE THREAD

**Issue by Susurrus** [mitsuhiko/fragile#6]
I have CI set up for many of my crates, and it broke when I updated some dependencies, because `rust-fragile` was included. The Rust version I use is too old, but finding the minimum supported version wasn't as quick as just reading the README here. I've seen this done for other crates and I think it'd be very helpful if it was documented here as well.

**Comment by Susurrus** [comment]
I thought it was 1.22 with the errors that I saw, but it looks to be 1.26.

**Comment by mitsuhiko** [comment]
Added
